[data]
    annotation_path = "/home/frank/datasets/VOC2012/JSONAnnotation/annotation.json"
    label_path = "/home/frank/datasets/VOC2012/JSONAnnotation/labels.json"

[transforms]
    target_image_size = 224
    patch_size = 16

[training]
    batch_size = 96
    epochs = 25
    lr = 0.0001
    num_workers = 2
    weight_decay = 0.0001

[tokenizer]
    max_seq_len = 300

[encoder]
    pretrained_encoder = "facebook/deit-base-distilled-patch16-224"
    encoder_bottleneck = 256

[decoder]
    num_decoder_layers = 6
    decoder_layer_dim = 256
    num_heads = 2
